eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8901
spring:
  application:
    name: service-wallet
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-customer