eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8092
spring:
  application:
    name: service-credit
  data:
    mongodb:
      database: ms-customer
      uri: mongodb://p3mongodb:WFve1bGHSZWShJdNllhEgbUqesNFhZqiiomgtst2GGBDphIpDNzSzuJU3GXqGqRARBgFozHjDsjpxj3JHcNVMg==@p3mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@p3mongodb@