eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
spring:
  application:
    name: service-bill
  data:
    mongodb:
      database: ms-customer
      uri: mongodb://p3mongodb:WFve1bGHSZWShJdNllhEgbUqesNFhZqiiomgtst2GGBDphIpDNzSzuJU3GXqGqRARBgFozHjDsjpxj3JHcNVMg==@p3mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@p3mongodb@
  kafka:
      bootstrap-servers: ${kafka.server.hostname}:${kafka.server.port}

kafka:
  server:
    hostname: 192.168.1.5
    port: 29092
  topic:
    name: bill-topic
    partitions: 1
    replicas: 1
    groupid: bill-group
  consumer:
    acquisition: acquisition-topic
    transaction: transaction-topic