eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8081
spring:
    application:
        name: service-customer
    data:
        mongodb:
            database: ms-customer
            uri: mongodb://p3mongodb:WFve1bGHSZWShJdNllhEgbUqesNFhZqiiomgtst2GGBDphIpDNzSzuJU3GXqGqRARBgFozHjDsjpxj3JHcNVMg==@p3mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@p3mongodb@
kafka:
    server:
        hostname: 192.168.1.5
        port: 29092
    topic:
        name: customer-topic
        partitions: 1
        replicas: 1
        groupid: customer-group
    producer:
        customer: wallet-topic
    consumer:
        wallet: created-customer-topic
        #bill: bill-topic
        #acquisition: acquisition-topic
        #customer: customer-topic

msg:
    error:
        registro:
            notfound: CLIENT NOT FOUND
            notfound.update: THE CLIENT CANNOT BE UPDATED

resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 2s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - java.util.concurrent.TimeoutException
                    - java.io.IOException
                    - java.net.ConnectException
        instances:
            customerServiceCircuitBreaker:
                baseConfig: default