eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8087
spring:
  application:
    name: service-acquisition
  data:
    mongodb:
      host: p3mongodb.mongo.cosmos.azure.com
      port: 10255
      username: p3mongodb
      password: WFve1bGHSZWShJdNllhEgbUqesNFhZqiiomgtst2GGBDphIpDNzSzuJU3GXqGqRARBgFozHjDsjpxj3JHcNVMg==
      database: ms-customer